1) Docker 101

https://docker-curriculum.com/

https://labs.play-with-docker.com/

https://www.katacoda.com/courses/docker

https://itnext.io/docker-101-fundamentals-the-dockerfile-b33b59d0f14b



2) OpenShift 101

https://learn.openshift.com/

https://blog.openshift.com/

https://docs.openshift.com/container-platform/3.9/welcome/index.html


3) Kubernetes 101

https://kubernetes.io/docs/tutorials/kubernetes-basics/

https://www.edx.org/course/fundamentals-containers-kubernetes-red-red-hat-do081x

https://labs.play-with-k8s.com/

https://www.katacoda.com/courses/kubernetes
